# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9

    working_directory: ~/repo
    steps:
      - checkout
      
      - run: |
          echo "deb http://deb.debian.org/debian stretch-backports main" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://deb.debian.org/debian stretch-backports main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y libsodium23 libsodium-dev

      - run: mix local.hex --force 
      - run: mix local.rebar --force

      - run: mix deps.get
      - run: mix db.reset
      - run: mix test